services:
  - type: web
    name: otohits-app
    runtime: docker
    repo: otohits/app
    region: oregon
    plan: standard
    rootDir: .
    dockerCommand: /otohits/run.sh
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: APPLICATION_KEY
        value: "31005816-9090-4eec-a74c-4237706545b9"
