services:
  - type: web
    name: prueba-oto
    runtime: docker
    repo: https://github.com/amordvita/prueba-oto.git
    region: oregon
    plan: standard
    rootDir: .
    dockerCommand: /otohits/run.sh
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: APPLICATION_KEY
        value: "31005816-9090-4eec-a74c-4237706545b9"
