services:
  - name: app
    env:
      APPLICATION_KEY: "31005816-9090-4eec-a74c-4237706545b9"
    envSecrets:
      - source: APPLICATION_KEY
    buildCommand: "docker build -t $RENDER_SERVICE_NAME -f Dockerfile ."
    startCommand: "docker run -p $PORT:$PORT $RENDER_SERVICE_NAME"

routes:
  - path: "/*"
    memory: 512M
    concurrency:
      hard: 10
      soft: 5
    includeRequestBody: true
